title: 拨弦记
description: 世界弹拨乐资讯、音乐分享与知识记录
url: "https://keenkwok.github.io"
baseurl: "/boxianji"

theme: minima
markdown: kramdown

author:
  name: 拨弦记

lang: zh-CN

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed